spring:
  datasource:
    url: ${BOARD_POSTGRESQL_URL:jdbc:postgresql://localhost:5433/demo}
    username: ${BOARD_POSTGRESQL_USERNAME:root}
    password: ${BOARD_POSTGRESQL_PASSWORD:root}
  flyway:
    locations:
      - db/migration/v1
  data:
    redis:
      host: ${VALKEY_HOST:localhost}
      port: ${VALKEY_PORT:6378}
      password: ${VALKEY_PASSWORD:root}